<?php
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\Core\Block\BlockPluginInterface;
use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;


function d6_utilities_theme($existing, $type, $theme, $path) {
    return array(
        'front-our-services' => array(
            'variables' => array(
                'data' => array(),
            )
        )
    );
}







































?>